### ISSUE TITLE
Questions when replicating

### ISSUE THREAD

**Issue by kaishxu** [morecry/MISC#3]
Hello,

I was replicating your experiments, and there were some bugs in the code.
1. When running "BlenderEmotionalSupport.py", the sample number of "chat_texts" is inconsistent with that of "comet_st" in line 1183;
2. I tried to reconstruct the "comet_st", but a missing file, named "Situation2Comet.txt", made me stoped;
3. Unfortunately, no other public files can output the "Situation2Comet.txt";

Could you please share more codes or help me figure it out?
Thanks a lot!

**Comment by tintpham** [comment]
Hi,
I am running "BlenderEmotionalSupport.py" and there is an error in the line  1152
model = BlenderbotSmallForConditionalGeneration.from_pretrained(args.output_dir,
        from_tf=False)
The error log is as follows:
Traceback (most recent call last):
  File "/home/s2120419/PycharmProjects/MISC/BlenderEmotionalSupport.py", line 1332, in <module>
    generate(args)
  File "/home/s2120419/PycharmProjects/MISC/BlenderEmotionalSupport.py", line 1152, in generate
    model = BlenderbotSmallForConditionalGeneration.from_pretrained(args.output_dir,
  File "/home/s2120419/PycharmProjects/MISC/src/transformers/modeling_utils.py", line 951, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/home/s2120419/PycharmProjects/MISC/src/transformers/configuration_utils.py", line 372, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/s2120419/PycharmProjects/MISC/src/transformers/configuration_utils.py", line 432, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'blender_strategy/all_loss'. Make sure that:

- 'blender_strategy/all_loss' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'blender_strategy/all_loss' is the correct path to a directory containing a config.json file

It seems that the code cannot find the pretrained model. I am wondering if that pretrained model is the pretrained from the author or I just need to download from [huggingface blender_small?](https://huggingface.co/facebook/blenderbot_small-90M)?

**Comment by ashokchhetri7** [comment]
> Hi, I am running "BlenderEmotionalSupport.py" and there is an error in the line 1152 model = BlenderbotSmallForConditionalGeneration.from_pretrained(args.output_dir, from_tf=False) The error log is as follows: Traceback (most recent call last): File "/home/s2120419/PycharmProjects/MISC/BlenderEmotionalSupport.py", line 1332, in generate(args) File "/home/s2120419/PycharmProjects/MISC/BlenderEmotionalSupport.py", line 1152, in generate model = BlenderbotSmallForConditionalGeneration.from_pretrained(args.output_dir, File "/home/s2120419/PycharmProjects/MISC/src/transformers/modeling_utils.py", line 951, in from_pretrained config, model_kwargs = cls.config_class.from_pretrained( File "/home/s2120419/PycharmProjects/MISC/src/transformers/configuration_utils.py", line 372, in from_pretrained config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs) File "/home/s2120419/PycharmProjects/MISC/src/transformers/configuration_utils.py", line 432, in get_config_dict raise EnvironmentError(msg) OSError: Can't load config for 'blender_strategy/all_loss'. Make sure that:
> 
> * 'blender_strategy/all_loss' is a correct model identifier listed on 'https://huggingface.co/models'
> * or 'blender_strategy/all_loss' is the correct path to a directory containing a config.json file
> 
> It seems that the code cannot find the pretrained model. I am wondering if that pretrained model is the pretrained from the author or I just need to download from [huggingface blender_small?](https://huggingface.co/facebook/blenderbot_small-90M)?

I faced the same exact issue. I tried to see the HF link for it. https://huggingface.co/lsy641/ESC_Blender_Strategy/tree/main

But it doesn't have a config.json file, I don't know where to go from here. Any help is appreciated. I am using this paper as the baseline for my research. Else I will drop it ! :(
